spring:
  application:
    name: ai-code
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db04
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
      database: 0
  session:
    store-type: redis
    timeout: 259200


server:
  port: 8080 # 端口号
  servlet:
    context-path: /api # 后端访问的前缀
    session:
      cookie:
        max-age: 259200

# springdoc-openai后端调试工具(knife4j)
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.bobby.aicode.controller
knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-flex:
  configuration:
    # 日志实现，设置为StdOutImpl即可在控制台打印SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

langchain4j:
  community:
    dashscope:
      streaming-chat-model:
        api-key: ${DASHSCOPE_API_KEY}
        model-name: glm-5
        max-tokens: 8192
        parameters:
          enable-thinking: true
      chat-model:
        api-key: ${DASHSCOPE_API_KEY}
        model-name: glm-5
        max-tokens: 8192
        parameters:
          response-format: json
          enable-thinking: true


#// 在代码中构建模型时启用请求和响应日志
#ChatModel chatModel = QwenChatModel.builder()
#    .apiKey("${DASHSCOPE_API_KEY}")
#    .modelName("glm-4.7")
#    .logRequests(true)    // 启用请求日志记录
#    .logResponses(true)   // 启用响应日志记录
#    .build();
